### PR TITLE
Fix Bitcambio endpoint URL

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by jpereira** [comment]
The Android >= 10 is failing to work with the URL endpoint with `_`. After talking with @pinhopro (Blinktrade Owner), He created such a new entry without `_`.

**Comment by jpereira** [comment]
It would be great if you release a new apk with that change allowing to use the Blinktrade again.

**Comment by aneonex** [comment]
App already updated in Google Play.
Thank you for the PR.

**Comment by jpereira** [comment]
Now is working again. Thanks

**Pull request merged**
